server:
  port: 8081

session:
  token:
    expire: 300
  refresh_token:
    expire: 600

auth:
  platform_id: 77e2edcc9b40441200e31dc57dbb8829
  secret_key: 06848368e2647bf5ec493160c423d453
  auth_host: auth.system.com
  auth_port: 8088
  web_host: auth.system.com
  web_port: 8088
  get_access_token_path: /api/auth/access_token
  cache:
    max_records: 10000
    expired: 600
  cookie:
    open_id_alisa: open_id
    access_token_alisa: access_token
    user_name_alisa: user_name

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:13306/db_auth?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
     username: suxin
     password: suxin@2017
     driver-class-name: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource

     initialSize: 5
     # 配置获取连接等待超时的时间
     maxWait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     timeBetweenEvictionRunsMillis: 60000
     # 配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 300000
     validationQuery: SELECT 1 FROM DUAL
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     # 打开PSCache，并且指定每个连接上PSCache的大小
     poolPreparedStatements: true
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
     # 合并多个DruidDataSource的监控数据
     useGlobalDataSourceStat: true

  profiles:
    active: dev

